# Netlify configuration for ML Club Website
[build]
  # No build command needed for static site
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Redirect rules for clean URLs
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/main"
  to = "/index.html"
  status = 301

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA fallback for client-side routing (if needed in future)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}
